In [1]:
import os
import sys
import torch
import importlib
import pandas as pd
from sklearn.linear_model import Ridge

import utils
import evaluation_metrics as em
from datasets import load_dataset
from hkan.hkan import (
    Sigmoid, Gaussian, ReLU, Tanh, Softplus, Identity,
    make_hkan_layer, extend_hkan, set_tqdm_disable,
)
importlib.reload(utils)

/Users/gizemnurdal/miniconda3/envs/swim-meets-kans/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# TF1 Experiments

## HKAN

In [2]:
# Load TF1 dataset
tf1 = load_dataset("TF1")
tf1_x_train, tf1_x_test, tf1_y_train, tf1_y_test = tf1["train_input"], tf1["test_input"], tf1["train_label"], tf1["test_label"]

In [3]:
print("TF1 train describe")
display(pd.DataFrame(tf1_x_train).describe())
print("TF1 test describe")
display(pd.DataFrame(tf1_x_test).describe())
print("TF1 y_train describe")
display(pd.Series(tf1_y_train).describe())
print("TF1 y_test describe")
display(pd.Series(tf1_y_test).describe())

TF1 train describe

                 0            1
count  5000.000000  5000.000000
mean      0.502492     0.498871
std       0.291808     0.285606
min       0.000021     0.000020
25%       0.247467     0.253435
50%       0.504131     0.497807
75%       0.758499     0.743126
max       0.999705     0.999692

TF1 test describe

                  0             1
count  10000.000000  10000.000000
mean       0.500000      0.500000
std        0.291591      0.291591
min        0.000000      0.000000
25%        0.250000      0.250000
50%        0.500000      0.500000
75%        0.750000      0.750000
max        1.000000      1.000000

TF1 y_train describe

count    5000.000000
mean        0.505381
std         0.166339
min         0.009263
25%         0.414095
50%         0.501150
75%         0.600623
max         0.988818
dtype: float64

TF1 y_test describe

count    10000.000000
mean         0.500000
std          0.170042
min          0.000000
25%          0.404882
50%          0.500000
75%          0.595118
max          1.000000
dtype: float64

In [4]:
# TF1 HKAN model params
tf1_model_params = [
    {
        "layer": 0,
        "n_vars_out": 932,
        "basis_fn": Sigmoid(s=1),
        "n_basis": 2,
        "centers": "random_data_points",
        "expanding_base_regressor": Ridge(alpha=0.1),
    },
    {
        "layer": 1,
        "n_vars_out": 1,
        "basis_fn": Tanh(s=33),
        "n_basis": 13,
        "centers": "random_data_points",
        "expanding_base_regressor": Ridge(alpha=10),
    }
]
tf1_model = utils.build_hkan_model_from_configs(tf1_model_params)
tf1_model

Pipeline(steps=[('expanding_layer_0',
                 ExpandingLayer(base_regressor=Ridge(alpha=0.1),
                                basis_fn=<hkan.hkan.Sigmoid object at 0x17c604b90>,
                                centers='random_data_points', n_basis=2,
                                n_vars_out=932)),
                ('connecting_layer_0', ConnectingLayer()),
                ('expanding_layer_1',
                 ExpandingLayer(base_regressor=Ridge(alpha=10),
                                basis_fn=<hkan.hkan.Tanh object at 0x17aca8610>,
                                centers='random_data_points', n_basis=13,
                                n_vars_out=1)),
                ('connecting_layer_1', ConnectingLayer())])

In [5]:
# Fit HKAN for TF1
utils.fit_hkan(tf1_model,  tf1_x_train, tf1_y_train)
tf1_results = em.evaluate(
    tf1_model,
    tf1_x_train, tf1_y_train, tf1_x_test, tf1_y_test
)

Fitting 1D regressors: 100%|██████████| 1864/1864 [00:00<00:00, 2037.76it/s]
Fitting connecting regressors: 100%|██████████| 932/932 [00:00<00:00, 2808.10it/s]
Fitting 1D regressors: 100%|██████████| 932/932 [00:00<00:00, 1043.56it/s]
Fitting connecting regressors: 100%|██████████| 1/1 [00:00<00:00,  2.85it/s]

✓ HKAN training completed in 4.4548 seconds

In [6]:
em.print_results(tf1_results)

Metric          Train                Test
-------------------------------------------------------
MAE             1.077391e-11         1.226856e-11
RMSE            1.467517e-11         2.019119e-11
-------------------------------------------------------
Inference (s)   1.263086             1.807003

## KAN

In [7]:
tf1_kan_study = utils.study_optuna_kan("TF1_new", tf1_x_train, tf1_y_train, tf1_x_test, tf1_y_test, n_trials = 10)

[I 2026-07-20 15:07:54,736] A new study created in memory with name: no-name-e460c413-83cf-42bb-b6b2-e130f8604128

======================================================================
Optimizing KAN architecture with 5-Fold CV on TF1_new
======================================================================

  0%|          | 0/10 [00:00<?, ?it/s]

checkpoint directory created: ./model
saving model version 0.0

| train_loss: 1.67e-01 | test_loss: 1.62e-01 | reg: 1.79e-01 | : 100%|█| 50/50 [01:08<00:00,  1.37s/

saving model version 0.1
saving model version 0.2

| train_loss: 1.67e-01 | test_loss: 1.62e-01 | reg: 8.66e-02 | : 100%|█| 50/50 [01:10<00:00,  1.42s/

saving model version 0.3
saving model version 0.4

| train_loss: 1.67e-01 | test_loss: 1.62e-01 | reg: 2.85e-02 | : 100%|█| 50/50 [01:13<00:00,  1.47s/

saving model version 0.5
saving model version 0.6

| train_loss: 1.67e-01 | test_loss: 1.62e-01 | reg: 8.88e-03 | : 100%|█| 50/50 [01:17<00:00,  1.55s/

saving model version 0.7

✓ KAN training with grid extension completed in 290.4587 seconds
checkpoint directory created: ./model
saving model version 0.0

| train_loss: 1.66e-01 | test_loss: 1.69e-01 | reg: 6.32e-02 | : 100%|█| 50/50 [01:07<00:00,  1.36s/

saving model version 0.1
saving model version 0.2

| train_loss: 1.66e-01 | test_loss: 1.69e-01 | reg: 3.14e-02 | : 100%|█| 50/50 [01:15<00:00,  1.50s/

saving model version 0.3
saving model version 0.4

| train_loss: 1.66e-01 | test_loss: 1.69e-01 | reg: 2.07e-02 | : 100%|█| 50/50 [01:23<00:00,  1.67s/

saving model version 0.5
saving model version 0.6

| train_loss: 1.66e-01 | test_loss: 1.69e-01 | reg: 1.90e-02 | : 100%|█| 50/50 [01:34<00:00,  1.89s/

saving model version 0.7

✓ KAN training with grid extension completed in 321.4524 seconds
checkpoint directory created: ./model
saving model version 0.0

| train_loss: 1.66e-01 | test_loss: 1.68e-01 | reg: 1.83e-01 | : 100%|█| 50/50 [01:06<00:00,  1.32s/

saving model version 0.1
saving model version 0.2

| train_loss: 1.66e-01 | test_loss: 1.68e-01 | reg: 8.50e-02 | : 100%|█| 50/50 [01:05<00:00,  1.31s/

saving model version 0.3
saving model version 0.4

| train_loss: 1.66e-01 | test_loss: 1.68e-01 | reg: 2.73e-02 | : 100%|█| 50/50 [01:08<00:00,  1.37s/

saving model version 0.5
saving model version 0.6

| train_loss: 1.66e-01 | test_loss: 1.68e-01 | reg: 8.72e-03 | : 100%|█| 50/50 [01:22<00:00,  1.65s/

saving model version 0.7

✓ KAN training with grid extension completed in 282.7478 seconds
checkpoint directory created: ./model
saving model version 0.0

| train_loss: 1.66e-01 | test_loss: 1.66e-01 | reg: 2.56e-01 | : 100%|█| 50/50 [00:29<00:00,  1.69it

saving model version 0.1
saving model version 0.2

| train_loss: 1.66e-01 | test_loss: 1.66e-01 | reg: 1.29e-01 | : 100%|█| 50/50 [00:54<00:00,  1.08s/

saving model version 0.3
saving model version 0.4

| train_loss: 1.66e-01 | test_loss: 1.66e-01 | reg: 1.29e-01 | : 100%|█| 50/50 [00:36<00:00,  1.38it

saving model version 0.5
saving model version 0.6

| train_loss: 1.66e-01 | test_loss: 1.66e-01 | reg: 1.29e-01 | : 100%|█| 50/50 [00:40<00:00,  1.25it

saving model version 0.7

✓ KAN training with grid extension completed in 159.9754 seconds
checkpoint directory created: ./model
saving model version 0.0

| train_loss: 1.67e-01 | test_loss: 1.66e-01 | reg: 1.73e-01 | : 100%|█| 50/50 [01:10<00:00,  1.40s/

saving model version 0.1
saving model version 0.2

| train_loss: 1.67e-01 | test_loss: 1.66e-01 | reg: 8.40e-02 | : 100%|█| 50/50 [01:11<00:00,  1.42s/

saving model version 0.3
saving model version 0.4

| train_loss: 1.67e-01 | test_loss: 1.66e-01 | reg: 2.65e-02 | : 100%|█| 50/50 [01:11<00:00,  1.42s/

saving model version 0.5
saving model version 0.6

| train_loss: 1.67e-01 | test_loss: 1.66e-01 | reg: 8.04e-03 | : 100%|█| 50/50 [01:20<00:00,  1.60s/

saving model version 0.7

✓ KAN training with grid extension completed in 292.2729 seconds
checkpoint directory created: ./model
saving model version 0.0

| train_loss: 1.66e-01 | test_loss: 1.70e-01 | reg: 1.71e-01 | : 100%|█| 50/50 [01:52<00:00,  2.24s/

saving model version 0.1
saving model version 0.2

| train_loss: 1.66e-01 | test_loss: 1.70e-01 | reg: 8.29e-02 | : 100%|█| 50/50 [01:45<00:00,  2.10s/

saving model version 0.3
saving model version 0.4

| train_loss: 1.66e-01 | test_loss: 1.70e-01 | reg: 2.85e-02 | : 100%|█| 50/50 [01:49<00:00,  2.19s/

saving model version 0.5
saving model version 0.6

| train_loss: 1.66e-01 | test_loss: 1.70e-01 | reg: 8.09e-03 | : 100%|█| 50/50 [02:01<00:00,  2.42s/
Best trial: 0. Best value: 0.166323:  10%|█         | 1/10 [29:55<4:29:17, 1795.31s/it]

saving model version 0.7

✓ KAN training with grid extension completed in 448.1876 seconds
[I 2026-07-20 15:37:50,053] Trial 0 finished with value: 0.1663231507260548 and parameters: {'width_idx': 2}. Best is trial 0 with value: 0.1663231507260548.
checkpoint directory created: ./model
saving model version 0.0

| train_loss: 1.67e-01 | test_loss: 1.62e-01 | reg: 4.43e-01 | : 100%|█| 50/50 [01:21<00:00,  1.62s/

saving model version 0.1
saving model version 0.2

| train_loss: 1.67e-01 | test_loss: 1.62e-01 | reg: 5.11e-01 | : 100%|█| 50/50 [01:15<00:00,  1.50s/

saving model version 0.3
saving model version 0.4

| train_loss: 2.19e-01 | test_loss: 2.13e-01 | reg: 4.50e-01 | : 100%|█| 50/50 [01:26<00:00,  1.73s/

saving model version 0.5
saving model version 0.6

| train_loss: 3.62e-01 | test_loss: 3.59e-01 | reg: 2.28e+00 | : 100%|█| 50/50 [01:33<00:00,  1.88s/

saving model version 0.7

✓ KAN training with grid extension completed in 336.8265 seconds
checkpoint directory created: ./model
saving model version 0.0

| train_loss: 1.66e-01 | test_loss: 1.69e-01 | reg: 4.53e-01 | : 100%|█| 50/50 [01:19<00:00,  1.59s/

saving model version 0.1
saving model version 0.2

| train_loss: 2.33e-01 | test_loss: 2.39e-01 | reg: 4.53e-01 | : 100%|█| 50/50 [01:24<00:00,  1.69s/

saving model version 0.3
saving model version 0.4

| train_loss: 3.43e-01 | test_loss: 3.50e-01 | reg: 4.67e-01 | : 100%|█| 50/50 [00:22<00:00,  2.22it

saving model version 0.5
saving model version 0.6

| train_loss: 3.43e-01 | test_loss: 3.50e-01 | reg: 4.66e-01 | : 100%|█| 50/50 [00:13<00:00,  3.77it

saving model version 0.7

✓ KAN training with grid extension completed in 199.9212 seconds
checkpoint directory created: ./model
saving model version 0.0

| train_loss: 1.66e-01 | test_loss: 1.69e-01 | reg: 4.57e-01 | :  98%|▉| 49/50 [01:25<00:01,  1.75s/
Best trial: 0. Best value: 0.166323:  10%|█         | 1/10 [40:17<6:02:39, 2417.73s/it]

[W 2026-07-20 15:48:12,476] Trial 1 failed with parameters: {'width_idx': 8} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/Users/gizemnurdal/miniconda3/envs/swim-meets-kans/lib/python3.11/site-packages/optuna/study/_optimize.py", line 205, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/Users/gizemnurdal/Workspace/swim-meets-kans/utils.py", line 390, in <lambda>
    lambda trial: objective_kan(
                  ^^^^^^^^^^^^^^
  File "/Users/gizemnurdal/Workspace/swim-meets-kans/utils.py", line 299, in objective_kan
    model = fit_kan_with_grid_extension(model, X_fold_train, y_fold_train,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gizemnurdal/Workspace/swim-meets-kans/utils.py", line 222, in fit_kan_with_grid_extension
    model.fit(dataset, opt=opt, steps=steps_per_grid, lamb=lamb)
  File "/Users/gizemnurdal/Workspace/swim-meets-kans/pykan/kan/MultKAN.py", line 1555, in fit
    optimizer.step(closure)
  File "/Users/gizemnurdal/miniconda3/envs/swim-meets-kans/lib/python3.11/site-packages/torch/optim/optimizer.py", line 517, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gizemnurdal/miniconda3/envs/swim-meets-kans/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gizemnurdal/Workspace/swim-meets-kans/pykan/kan/LBFGS.py", line 443, in step
    loss, flat_grad, t, ls_func_evals = _strong_wolfe(
                                        ^^^^^^^^^^^^^^
  File "/Users/gizemnurdal/Workspace/swim-meets-kans/pykan/kan/LBFGS.py", line 50, in _strong_wolfe
    f_new, g_new = obj_func(x, t, d)
                   ^^^^^^^^^^^^^^^^^
  File "/Users/gizemnurdal/Workspace/swim-meets-kans/pykan/kan/LBFGS.py", line 442, in obj_func
    return self._directional_evaluate(closure, x, t, d)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gizemnurdal/Workspace/swim-meets-kans/pykan/kan/LBFGS.py", line 291, in _directional_evaluate
    loss = float(closure())
                 ^^^^^^^^^
  File "/Users/gizemnurdal/miniconda3/envs/swim-meets-kans/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gizemnurdal/Workspace/swim-meets-kans/pykan/kan/MultKAN.py", line 1521, in closure
    pred = self.forward(dataset['train_input'][train_id], singularity_avoiding=singularity_avoiding, y_th=y_th)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gizemnurdal/Workspace/swim-meets-kans/pykan/kan/MultKAN.py", line 826, in forward
    input_range = torch.std(preacts, dim=0) + 0.1
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2026-07-20 15:48:12,478] Trial 1 failed with value None.

KeyboardInterrupt:

In [ ]:
# Create TF1 KAN model with best architecture
tf1_kan_model = utils.build_kan(width=tf1_kan_study["architecture"], grid=3, k=3, seed=42)

In [ ]:
# Train and test TF1 KAN model
utils.fit_kan(tf1_kan_model, tf1_x_train, tf1_y_train, tf1_x_test, tf1_y_test, steps=100, opt="Adam", lamb=1e-3)

tf1_kan_results = em.evaluate(
    utils.KANModel(tf1_kan_model),
    tf1_x_train, tf1_y_train, tf1_x_test, tf1_y_test
)

In [ ]:
em.print_results(tf1_kan_results)

# TF2 Experiments

## HKAN

In [ ]:
# Load TF2 dataset
tf2 = load_dataset("TF2")
tf2_x_train, tf2_x_test, tf2_y_train, tf2_y_test = tf2["train_input"], tf2["test_input"], tf2["train_label"], tf2["test_label"]

In [ ]:
print("TF2 train describe")
display(pd.DataFrame(tf2_x_train).describe())
print("TF2 test describe")
display(pd.DataFrame(tf2_x_test).describe())
print("TF2 y_train describe")
display(pd.Series(tf2_y_train).describe())
print("TF2 y_test describe")
display(pd.Series(tf2_y_test).describe())

In [ ]:
# TF2 HKAN model params
tf2_model_params = [
    {
        "layer": 0,
        "n_vars_out": 48,
        "basis_fn": Tanh(s=22),
        "n_basis": 17,
        "centers": "random",
        "expanding_base_regressor": Ridge(alpha=0.1),
    },
    {
        "layer": 1,
        "n_vars_out": 11,
        "basis_fn": Softplus(s=18),
        "n_basis": 21,
        "centers": "random_data_points",
        "expanding_base_regressor": Ridge(alpha=1),
    },
    {
        "layer": 2,
        "n_vars_out": 1,
        "basis_fn": Identity(),
        # Default configuration
        "n_basis": 1,
        "centers": "equally_spaced",
        "expanding_base_regressor": None,
    }
]
tf2_model = utils.build_hkan_model_from_configs(tf2_model_params)
tf2_model

In [ ]:
# Fit HKAN for TF2
utils.fit_hkan(tf2_model, tf2_x_train, tf2_y_train)
tf2_results = em.evaluate(
    tf2_model,
    tf2_x_train, tf2_y_train, tf2_x_test, tf2_y_test
)

In [ ]:
em.print_results(tf2_results)

## KAN

In [ ]:
tf2_kan_study = utils.study_optuna_kan("TF2", tf2_x_train, tf2_y_train, tf2_x_test, tf2_y_test, n_trials=10)

In [ ]:
tf2_kan_model = utils.build_kan(width=tf2_kan_study["architecture"], grid=3, k=3, seed=42)

In [ ]:
utils.fit_kan(tf2_kan_model, tf2_x_train, tf2_y_train, tf2_x_test, tf2_y_test, steps=100, opt="Adam", lamb=1e-3)

tf2_kan_results = em.evaluate(
    utils.KANModel(tf2_kan_model),
    tf2_x_train, tf2_y_train, tf2_x_test, tf2_y_test
)

In [ ]:
em.print_results(tf2_kan_results)

# TF3 Experiments

## HKAN

In [ ]:
# Load TF3 dataset
tf3 = load_dataset("TF3")
tf3_x_train, tf3_x_test, tf3_y_train, tf3_y_test = tf3["train_input"], tf3["test_input"], tf3["train_label"], tf3["test_label"]

In [ ]:
print("TF3 train describe")
display(pd.DataFrame(tf3_x_train).describe())
print("TF3 test describe")
display(pd.DataFrame(tf3_x_test).describe())
print("TF3 y_train describe")
display(pd.Series(tf3_y_train).describe())
print("TF3 y_test describe")
display(pd.Series(tf3_y_test).describe())

In [ ]:
# TF3 HKAN model params
tf3_model_params = [
    {
        "layer": 0,
        "n_vars_out": 924,
        "basis_fn": Tanh(s=50),
        "n_basis": 39,
        "centers": "random",
        "expanding_base_regressor": Ridge(alpha=0.001),
    },
    {
        "layer": 1,
        "n_vars_out": 1,
        "basis_fn": Identity(),
        "n_basis": 1,
        "centers": "equally_spaced",
        "expanding_base_regressor": None,
    }
]
tf3_model = utils.build_hkan_model_from_configs(tf3_model_params)
tf3_model

In [ ]:
# Fit HKAN for TF3
utils.fit_hkan(tf3_model, tf3_x_train, tf3_y_train)
tf3_results = em.evaluate(
    tf3_model,
    tf3_x_train, tf3_y_train, tf3_x_test, tf3_y_test
)

In [ ]:
em.print_results(tf3_results)

## KAN

In [ ]:
tf3_kan_study = utils.study_optuna_kan("TF3", tf3_x_train, tf3_y_train, tf3_x_test, tf3_y_test, n_trials=10)

In [ ]:
tf3_kan_model = utils.build_kan(width=tf3_kan_study["architecture"], grid=3, k=3, seed=42)

In [ ]:
utils.fit_kan(tf3_kan_model, tf3_x_train, tf3_y_train, tf3_x_test, tf3_y_test, steps=100, opt="Adam", lamb=1e-3)

tf3_kan_results = em.evaluate(
    utils.KANModel(tf3_kan_model),
    tf3_x_train, tf3_y_train, tf3_x_test, tf3_y_test
)

In [ ]:
em.print_results(tf3_kan_results)

# TF4 Experiments

## HKAN

In [ ]:
# Load TF4 dataset
tf4 = load_dataset("TF4")
tf4_x_train, tf4_x_test, tf4_y_train, tf4_y_test = tf4["train_input"], tf4["test_input"], tf4["train_label"], tf4["test_label"]

In [ ]:
print("TF4 train describe")
display(pd.DataFrame(tf4_x_train).describe())
print("TF4 test describe")
display(pd.DataFrame(tf4_x_test).describe())
print("TF4 y_train describe")
display(pd.Series(tf4_y_train).describe())
print("TF4 y_test describe")
display(pd.Series(tf4_y_test).describe())

In [ ]:
# TF4 HKAN model params
tf4_model_params = [
    {
        "layer": 0,
        "n_vars_out": 1,
        "basis_fn": Tanh(s=3),
        "n_basis": 2,
        "centers": "equally_spaced",
        "expanding_base_regressor": Ridge(alpha=0.001),
    }
]
tf4_model = utils.build_hkan_model_from_configs(tf4_model_params)
tf4_model

In [ ]:
# Fit HKAN for TF4
utils.fit_hkan(tf4_model, tf4_x_train, tf4_y_train)
tf4_results = em.evaluate(
    tf4_model,
    tf4_x_train, tf4_y_train, tf4_x_test, tf4_y_test
)

In [ ]:
em.print_results(tf4_results)

## KAN

In [ ]:
tf4_kan_study = utils.study_optuna_kan("TF4", tf4_x_train, tf4_y_train, tf4_x_test, tf4_y_test, n_trials=10)

In [ ]:
tf4_kan_model = utils.build_kan(width=tf4_kan_study["architecture"], grid=3, k=3, seed=42)

In [ ]:
utils.fit_kan(tf4_kan_model, tf4_x_train, tf4_y_train, tf4_x_test, tf4_y_test, steps=100, opt="Adam", lamb=1e-3)

tf4_kan_results = em.evaluate(
    utils.KANModel(tf4_kan_model),
    tf4_x_train, tf4_y_train, tf4_x_test, tf4_y_test
)

In [ ]:
em.print_results(tf4_kan_results)

# TF5 Experiments

## HKAN

In [ ]:
# Load TF5 dataset
tf5 = load_dataset("TF5")
tf5_x_train, tf5_x_test, tf5_y_train, tf5_y_test = tf5["train_input"], tf5["test_input"], tf5["train_label"], tf5["test_label"]

In [ ]:
print("TF5 train describe")
display(pd.DataFrame(tf5_x_train).describe())
print("TF5 test describe")
display(pd.DataFrame(tf5_x_test).describe())
print("TF5 y_train describe")
display(pd.Series(tf5_y_train).describe())
print("TF5 y_test describe")
display(pd.Series(tf5_y_test).describe())

In [ ]:
# tf5 HKAN model params
tf5_model_params = [
    {
        "layer": 0,
        "n_vars_out": 912,
        "basis_fn": Tanh(s=50),
        "n_basis": 23,
        "centers": "random",
        "expanding_base_regressor": Ridge(alpha=0.01),
    },
    {
        "layer": 1,
        "n_vars_out": 1,
        "basis_fn": Identity(),
        "n_basis": 1,
        "centers": "equally_spaced",
        "equally_spaced": None,
    }
]
tf5_model = utils.build_hkan_model_from_configs(tf5_model_params)
tf5_model

In [ ]:
# Fit HKAN for TF5
utils.fit_hkan(tf5_model, tf5_x_train, tf5_y_train)
tf5_results = em.evaluate(
    tf5_model,
    tf5_x_train, tf5_y_train, tf5_x_test, tf5_y_test
)

In [ ]:
em.print_results(tf5_results)

## KAN

In [ ]:
tf5_kan_study = utils.study_optuna_kan("TF5", tf5_x_train, tf5_y_train, tf5_x_test, tf5_y_test, n_trials=10)

In [ ]:
tf5_kan_model = utils.build_kan(width=tf5_kan_study["architecture"], grid=3, k=3, seed=42)

In [ ]:
utils.fit_kan(tf5_kan_model, tf5_x_train, tf5_y_train, tf5_x_test, tf5_y_test, steps=100, opt="Adam", lamb=1e-3)

tf5_kan_results = em.evaluate(
    utils.KANModel(tf5_kan_model),
    tf5_x_train, tf5_y_train, tf5_x_test, tf5_y_test
)

In [ ]:
em.print_results(tf5_kan_results)